development:
  adapter: postgresql
  encoding: unicode
  database: mountain
  pool: 5
  username: nickhould
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mountain
  pool: 5
  username: nickhould
  password:
