require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuthorizationsController do

  # This should return the minimal set of attributes required to create a valid
  # Authorization. As you add validations to Authorization, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthorizationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all authorizations as @authorizations" do
      authorization = Authorization.create! valid_attributes
      get :index, {}, valid_session
      assigns(:authorizations).should eq([authorization])
    end
  end

  describe "GET show" do
    it "assigns the requested authorization as @authorization" do
      authorization = Authorization.create! valid_attributes
      get :show, {:id => authorization.to_param}, valid_session
      assigns(:authorization).should eq(authorization)
    end
  end

  describe "GET new" do
    it "assigns a new authorization as @authorization" do
      get :new, {}, valid_session
      assigns(:authorization).should be_a_new(Authorization)
    end
  end

  describe "GET edit" do
    it "assigns the requested authorization as @authorization" do
      authorization = Authorization.create! valid_attributes
      get :edit, {:id => authorization.to_param}, valid_session
      assigns(:authorization).should eq(authorization)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Authorization" do
        expect {
          post :create, {:authorization => valid_attributes}, valid_session
        }.to change(Authorization, :count).by(1)
      end

      it "assigns a newly created authorization as @authorization" do
        post :create, {:authorization => valid_attributes}, valid_session
        assigns(:authorization).should be_a(Authorization)
        assigns(:authorization).should be_persisted
      end

      it "redirects to the created authorization" do
        post :create, {:authorization => valid_attributes}, valid_session
        response.should redirect_to(Authorization.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved authorization as @authorization" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authorization.any_instance.stub(:save).and_return(false)
        post :create, {:authorization => {}}, valid_session
        assigns(:authorization).should be_a_new(Authorization)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authorization.any_instance.stub(:save).and_return(false)
        post :create, {:authorization => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested authorization" do
        authorization = Authorization.create! valid_attributes
        # Assuming there are no other authorizations in the database, this
        # specifies that the Authorization created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Authorization.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => authorization.to_param, :authorization => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested authorization as @authorization" do
        authorization = Authorization.create! valid_attributes
        put :update, {:id => authorization.to_param, :authorization => valid_attributes}, valid_session
        assigns(:authorization).should eq(authorization)
      end

      it "redirects to the authorization" do
        authorization = Authorization.create! valid_attributes
        put :update, {:id => authorization.to_param, :authorization => valid_attributes}, valid_session
        response.should redirect_to(authorization)
      end
    end

    describe "with invalid params" do
      it "assigns the authorization as @authorization" do
        authorization = Authorization.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authorization.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorization.to_param, :authorization => {}}, valid_session
        assigns(:authorization).should eq(authorization)
      end

      it "re-renders the 'edit' template" do
        authorization = Authorization.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authorization.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorization.to_param, :authorization => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authorization" do
      authorization = Authorization.create! valid_attributes
      expect {
        delete :destroy, {:id => authorization.to_param}, valid_session
      }.to change(Authorization, :count).by(-1)
    end

    it "redirects to the authorizations list" do
      authorization = Authorization.create! valid_attributes
      delete :destroy, {:id => authorization.to_param}, valid_session
      response.should redirect_to(authorizations_url)
    end
  end

end
